server:
    port: 80
spring:
    application:
        name: GimyApi
    datasource:
        url: jdbc:mariadb://localhost:3306/gimy?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: ${SPRING_DB_USER}
        password: ${SPRING_DB_PASS}
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true
    security:
        filter:
            order: 10
jwt:
    secret: ${SPRING_JWT_SECRET}
    expiration: 86400000 # 1 day
#    refresh-token:
#        expiration: 604800000 # 7 days
